GET http://localhost:3001/api/persons/3

###
GET http://localhost:3001/api/persons/


###
DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"JaiRaj",
    "number":"9031977952"
}